name: Continuous Testing

on:
  push:
    branches:
      - main
      - develop

permissions:
  contents: read

jobs:
  testing:
    name: Unit Testing
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: ${{ vars.JAVA_VERSION || '21' }}
          cache: maven

      - name: Run Unit Test
        run: mvn -B test